title: <p align="center"> Joey Huang </p> # your name (or website title) here

logo: "/images/circle-personal.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/JHuangCV2021.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/huangjpc/">LinkedIn</a> |
  <a href="https://github.com/jpchuang">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently pursuing a MSc. degree in Aerospace Engineering in the department of Control & Simulation at Delft University of Technology.
  <br><br>

  At this very moment, I have started my MSc. graduate thesis at the MAVLab research center where I focus on intelligent multi-modal locomotion of UAVs. For this specific reason, I have created this minimalistic porfolio / blog where I will (try) to actively keep up a journal of my progression and academic findings.

  <br><br>

  In addition, I will also use this portfolio to write any journeys of my futures endeavours in the exciting field of UAVs, Control Theory and many more! 
  <br><br>

  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
